//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telemetry.StorageProviders {


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class AzureStorageResources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal AzureStorageResources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Telemetry.CommonProviders.StorageProviders.AzureStorageResources", typeof(AzureStorageResources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
		///&lt;AzureTable&gt;
		///	&lt;Column&gt;
		///		&lt;AzureColumnName&gt;_ActivityTime&lt;/AzureColumnName&gt;
		///		&lt;DataPoint&gt;ActivityTime&lt;/DataPoint&gt;	
		///	&lt;/Column&gt;
		///	&lt;Column&gt;
		///		&lt;AzureColumnName&gt;_ErrorCode&lt;/AzureColumnName&gt;
		///		&lt;DataPoint&gt;ErrorCode&lt;/DataPoint&gt;
		///	&lt;/Column&gt;
		///	&lt;Column&gt;
		///		&lt;AzureColumnName&gt;_StatusCode&lt;/AzureColumnName&gt;
		///		&lt;DataPoint&gt;StatusCode&lt;/DataPoint&gt;
		///	&lt;/Column&gt;
		///	&lt;Column&gt;
		///		&lt;AzureColumnName&gt;Exception&lt;/AzureColumnName&gt;
		///		&lt;DataPoint&gt;Exception&lt;/DataPoint&gt;
		///	&lt;/Column&gt;
		///	&lt;Column&gt;
		///		&lt;Azu [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string DefaultAzureTableSchema {
			get {
				return ResourceManager.GetString("DefaultAzureTableSchema", resourceCulture);
			}
		}

	}

}
